### ISSUE TITLE
Crash on "Clean Solution" with Visual Studio 2012

### ISSUE THREAD

**Issue by jessevernon** [thomaslevesque/AutoRunCustomTool#9] opened 2015-07-22 20:51 UTC
Non-deterministic crash on a developer machine running Visual Studio 2012:
1) Enable AutoRunCustomTool
2) Go to Build -> Clean Solution
Expected: solution is cleaned
Actual: on some developer machines, Visual Studio crashes

3) Disable AutoRunCustomTool
4) Go to Build -> Clean Solution
Expected: solution is cleaned
Actual: solution is cleaned on all developer machines, no crashes

Here is a link to the Visual Studio crash dump: http://panoptoscratch.s3.amazonaws.com/hohno/GBejUD9AvdjOFOJmuqmP/devenv.dmp

Automatic analysis said the following:
Thread 0 - System ID 11120

Entry point	  devenv!WinMainCRTStartup
Create time	  7/22/2015 11:45:38 AM
Time spent in user mode	  0 Days 00:00:15.366
Time spent in kernel mode	  0 Days 00:00:02.496

This thread is not fully resolved and may or may not be a problem. Further analysis of these threads may be required.

The thread has evidence of .net exceptions on the stack. Check the Previous .NET Exceptions Report (Exceptions in all .NET Thread Stacks) to view more details of the associated exception 

.NET Call Stack

Function
[[HelperMethodFrame_1OBJ] (System.StubHelpers.InterfaceMarshaler.ConvertToManaged)] System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr, IntPtr, IntPtr, Int32)
DomainNeutralILStubClass.IL_STUB_COMtoCLR(IntPtr, IntPtr)+55
[[ComMethodFrame]]
DomainNeutralILStubClass.IL_STUB_CLRtoCOM()+95
[[InlinedCallFrame]]
Microsoft.VisualStudio.ORDesigner.CodeGenerator.CodeGenUtils.IsUsingDefaultCustomTool(EnvDTE.ProjectItem)+23
Microsoft.VisualStudio.ORDesigner.Common.MyProjectUtil+d__6.MoveNext()+c3
Microsoft.VisualStudio.ORDesigner.DslPackage.ORDesignerObjectsPackage.Microsoft.VisualStudio.Shell.Interop.IVsUpdateSolutionEvents2.UpdateProjectCfg_Done(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, Microsoft.VisualStudio.Shell.Interop.IVsCfg, Micro+aa
DomainNeutralILStubClass.IL_STUB_COMtoCLR(IntPtr, IntPtr, IntPtr, Int32, Int32, Int32)+79
[[ComMethodFrame]]
Microsoft_VisualStudio_Shell_UI_Internal_ni!DomainNeutralILStubClass.IL_STUB_CLRtoCOM(Microsoft.VisualStudio.Shell.Interop.IVsTask, UInt32, Microsoft.VisualStudio.Shell.Interop.IVsTask[], System.Object ByRef)+f2
[[InlinedCallFrame]]
Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.Services.VsTask+<>c__DisplayClass2c.b__2b(System.Threading.Tasks.Task`1[])+9a
Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.Services.VsTask+<>c__DisplayClass32.b__31()+22

**Comment by thomaslevesque** [comment] 2015-07-22 21:34
Thanks for the detailed report, I'll look into it. It's going to take a while just to download the dump, tough, because the site where it's hosted seems to have very limited bandwidth.

Which other VS extensions do you have installed? What's different between the machines where it crashes and the ones where it doesn't? Have you reproduced the problem with other VS versions?

**Comment by thomaslevesque** [comment] 2015-07-22 22:10
Forget what I said about the download site being slow; for some reason the download failed, and when I retried it transferred at 10MB/s ;)

**Comment by jessevernon** [comment] 2015-07-22 22:14
Awesome! Thanks Thomas! Let me know if you ultimately can't download the dump. It's 1GB, but it is hosted on S3, so hopefully you'll be able to get it.

We looked at the extensions on the developer's machine that has the crash, and disabled all of them except for the TFS extensions, which are also enabled on my machine, and the problem still repros on his machine, but not mine. So the other extensions don't appear to be correlated.

Let me know if you need any more information.

**Comment by thomaslevesque** [comment] 2015-07-22 22:50
Here's what I've been able to find so far:
- The crash is caused by an `ExecutionEngineException`, which indicates a serious CLR failure.
- The finalizer thread was finalizing an instance of `PropertyExtender`, which is a class from AutoRunCustomTool (the finalizer code is [here](https://github.com/thomaslevesque/AutoRunCustomTool/blob/master/AutoRunCustomTool/PropertyExtender.cs#L27-L38)). I suspect the call to `_extenderSite.NotifyDelete` does something seriously wrong that causes the CLR to crash. If I debug the dump with managed+native, I can see that the finalizer is calling into native code (`IExtenderSite` is a COM interface), but I don't know what it's doing exactly. If that's indeed the cause of the problem, I'm not sure what I can do, since I don't own that code...

Does the crash occur only on one machine? If so, it might be because something is corrupted on that machine...

**Comment by jessevernon** [comment] 2015-07-24 01:06
Thanks for taking a look! That's interesting. Why was AutoRunCustomTool being invoked on Clean Solution at all? Seems like it should be invoked on file saves?

On our end, it looks like this crash is somehow tied with WiX (shocker :). When we unload all WiX projects from our Solution we can Clean Solution without problem. When a WiX project is loaded, we will hit this bug. It also appears to be non-deterministic, perhaps being more likely if there are a large number of projects and WiX projects present.

Unfortunately I've been unable to create a simple repro for you to try out. I'll keep trying. In the meantime, I'd be curious to hear why AutoRunCustomTool code is even running on Clean Solution. Seems like if we could avoid that it would fix our issue.

**Comment by thomaslevesque** [comment] 2015-07-24 08:55
ARCT isn't actually invoked on Clean (in the sense that it doesn't run the custom tools), but since it creates `PropertyExtender` objects to hold the value of the "Run custom tool on" property, these objects must be GC'd at some point. Apparently it happens when you clean the solution, not sure why.

**Comment by jessevernon** [comment] 2015-07-27 21:54
Ah, that makes sense. I downloaded your source code and was able to reproduce the crash with a private build. I then added some multi-threading protection in the finalizer and was unable to reproduce the crash afterwards. Something along the lines of:

    ~PropertyExtender()
    {
        try
        {
            lock (this)
            {
                if (_extenderSite != null)
                {
                    _extenderSite.NotifyDelete(_cookie);
                    _extenderSite = null;
                }
            }
        }
        catch(Exception ex)
        {
            Debug.WriteLine("Error in PropertyExtender finalizer: {0}", ex);
        }
    }

What're your thoughts about a change like this? Admittedly, I have very little idea what I'm doing since I've never authored a VS extension, nor taken the time to understand how yours works, but given that this issue is non-deterministic, locking around the problem seemed like a good idea, and this definitely seems to have made things more stable. Our solution has around 200 C++, C# and WiX projects, by the way.

**Comment by thomaslevesque** [comment] 2015-07-27 23:02
Hi Jesse,

I'm glad you were able to reproduce the issue and find a fix. I'm not sure how the fix works, because no other code is locking on the `PropertyExtender` object (unless VS does it, which is hard to tell), and I don't think it's possible for the finalizer to run twice concurrently (since there's only one finalizer thread).

If you're 100% sure that it fixes the problem for you, please create a pull request, and I'll create a new release to include the fix.

**Comment by jessevernon** [comment] 2015-07-29 20:22
Thanks for the reply! I was under the same impression.

Interestingly, it looks like I was incorrect about being able to reproduce the issue with a private build from VS2012. I reverted my (probably incorrect) "fix" and tried again to reproduce the problem with just the code from trunk, backported to VS2012. Turns out I am actually unable to reproduce the problem at all with that build, "fix" or no fix. I then tried again with the binary available on GitHub (presumably built with VS2013) and am still able to reproduce the instability.

Do you think it's possible that building this tool with the VS2013 SDK has some potential stability implications for running in VS2012? Should there maybe be a separate version of the binary?

Anyway, we are going to run the private build that I backported to VS2012 for now since that seems to fix all the non-deterministic crashes we have been seeing. I can close this issue if you'd like. Thanks again for the quick and thorough replies! And the awesome tool!

**Comment by thomaslevesque** [comment] 2015-07-29 20:48
Hi Jesse,

I'm glad you managed to make a build that works for you.

> Do you think it's possible that building this tool with the VS2013 SDK has some potential stability implications for running in VS2012? Should there maybe be a separate version of the binary?

No idea. A separate version of the binary shouldn't be necessary, in theory. In any case, as I'm sure you understand, I'm not going to maintain separate versions of this tool for older VS version. I don't even have VS2013 anymore on my machine, I switched to VS2015.

**Closed by thomaslevesque** 2015-07-29 20:48 UTC
