### ISSUE TITLE
Does not work with ResX Manager

### ISSUE THREAD

**Issue by DarthSonic** [thomaslevesque/AutoRunCustomTool#23] opened 2019-04-15 08:16 UTC
Hi,

I am using ResX Manager extension to edit my .resx files. Unfortunatly AutoRunCustomTool does only work when I open the .resx files in Visual Studio's integrated editor, not when I am using ResX Manager.

Is it possible to get AutoRunCustomTool working with ResX Manager?

**Comment by thomaslevesque** [comment] 2019-04-15 08:22
Hi @DarthSonic,

AutoRunCustom tool reacts to an event that is raised in Visual Studio when a file is saved. I suspect ResX Manager doesn't raise this event (probably just accesses the file system directly), so AutoRunCustomTool can't detect it.

A possible fix could be to listen to file system changes directly. I'll think about it.

**Comment by thomaslevesque** [comment] 2020-03-22 11:07
I'm going to close this issue, as it's a duplicate of #17

**Closed by thomaslevesque** 2020-03-22 11:07 UTC
