### ISSUE TITLE
Missing "Run custom tool on" property

### ISSUE THREAD

**Issue by BasSchurink** [thomaslevesque/AutoRunCustomTool#29] opened 2021-05-18 10:26 UTC
On all files I still get the properties **"Custom tool"** and **"Custom Tool namespace"**.
The new property **"Run custom tool on"** is not available.

Anyone else got the same problem?

Visual Studio  : Enterprise 2019 v16.8.6
AutoRunCustomTool : v3.0.1

**Comment by MBroertjes** [comment] 2021-05-18 10:58
Yeah, the same goes for me, using Visual Studio 2019 and the latest version of AutoRunCustomTool.

Could there be a conflict with other 3rd party tools, like ReSharper?

**Comment by thomaslevesque** [comment] 2021-05-18 11:48
What kind of project is it? SDK-style (.NET Core / .NET 5) or "classic" csproj ?
Unfortunately this extension doesn't work on the new SDK-style project, and I don't know how to fix it. See #18 for details.

**Comment by thomaslevesque** [comment] 2021-12-19 16:11
With no feedback from the OP, I'm going to close this as a duplicate of #18

**Closed by thomaslevesque** 2021-12-19 16:11 UTC
